apiVersion: apps/v1
kind: Deployment
metadata:
  name: devdna-redis
  namespace: devdna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devdna-redis
  template:
    metadata:
      labels:
        app: devdna-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          command: ["redis-server", "--appendonly", "yes"]
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: devdna-redis
  namespace: devdna
spec:
  selector:
    app: devdna-redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: devdna
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
